# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_recommendation.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1avideo_recommendation.proto\x12\x05video\"V\n\x15RecommendationRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x14\n\x0cwatchHistory\x18\x02 \x03(\t\x12\x17\n\x0fsuccessfulPlays\x18\x03 \x03(\t\"*\n\x16RecommendationResponse\x12\x10\n\x08videoIds\x18\x01 \x03(\t2h\n\x13VideoRecommendation\x12Q\n\x12GetRecommendations\x12\x1c.video.RecommendationRequest\x1a\x1d.video.RecommendationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_recommendation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=37
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=123
  _globals['_RECOMMENDATIONRESPONSE']._serialized_start=125
  _globals['_RECOMMENDATIONRESPONSE']._serialized_end=167
  _globals['_VIDEORECOMMENDATION']._serialized_start=169
  _globals['_VIDEORECOMMENDATION']._serialized_end=273
# @@protoc_insertion_point(module_scope)
